spring:
  application:
    name: shared-expense-splitting-application

  datasource:
    url: jdbc:mysql://localhost:3306/expense_splitting_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info